extends: airbnb-base
env:
  node: true
rules:
  comma-dangle: [2, never]
  max-len: [1, 120, 2, { ignoreUrls: true, ignoreComments: false }]
  arrow-body-style: 0
  no-mixed-operators: 0
  no-shadow: [2, { allow: [err, error] }]
  no-console: 2
  no-underscore-dangle: 0
  guard-for-in: 0
  no-param-reassign: [error, { props: false }]
  no-eq-null: 2

  # custom
  class-methods-use-this: 0
